name: Healthcheck

on: [push]
# below block is run every 5 mins and every 7 mins
#  schedule:
#    - cron: "0/5 * * * *"
#    - cron: "0/7 * * * *"

jobs:
  run-health-check:
    strategy:
      matrix:
        runner: [macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: desktop disk-usage 
        id: step1
        run:
          du -hH -d 1 ~/Desktop
      - name: Library disk-usage
        id: step2
        run:
          du -hH -d 1 ~/Library/Developer
      - name: cpu usage
        id: step3 
        run:
          ps -A -o %cpu | awk '{s+=$1} END {print "CPU " s "%"}'
      - name: memory usage
        id: step4
        run:
          ps -A -o %mem | awk '{s+=$1} END {print "Memory " s "%"}'
      - name: notifications
        env:
          Step_1: $${{ steps.step1.conclusion}}
          Step_2: $${{ steps.step2.conclusion}}
          Step_3: $${{ steps.step3.conclusion}}
          Step_4: $${{ steps.step4.conclusion}}
        run: |
          echo "${{ steps.step1.name }} ${{ env.Step1 }}"
          echo "${{ steps.step2.name }} ${{ env.Step2 }}"
          echo "${{ steps.step3.name }} ${{ env.Step3 }}"
          echo "${{ steps.step4.name }} ${{ env.Step4 }}"
