name: Healthcheck

on:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  run-health-check:
    runs-on: macos-latest
    steps:
      - name: Healthcheck
        run: |
          du -hH -d 1 ~/Desktop
       