name: Healthcheck

on: [push]
# below block is run every 5 mins and every 7 mins
#  schedule:
#    - cron: "0/5 * * * *"
#    - cron: "0/7 * * * *"

jobs:
  run-health-check:
    strategy:
      matrix:
        runner: [macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: desktop disk-usage 
        id: desktop_disk_usage
        run:
          du -hH -d 1 ~/Desktop
        if: ${{ always() }}
      - name: Library disk-usage
        id: Library_disk_usage
        run:
          du -hH -d 1 ~/Library/Developer
        if: ${{ always() }}
      - name: cpu usage
        id: cpu_usage
        run:
          ps -A -o %cpu | awk '{s+=$1} END {print "CPU " s "%"}'
        if: ${{ always() }}
      - name: memory usage
        id: memory_usage
        run:
          ps -A -o %mem | awk '{s+=$1} END {print "Memory " s "%"}'
        if: ${{ always() }}
      - name: Post Notifications
        id: post_notification
        env:
          step1: ${{ jobs.run-health-check.steps.desktop_disk_usage.name }}
          step1_conc: ${{ jobs.run-health-check.steps.desktop_disk_usage.conclusion }}
          STEPS_CONTEXT: ${{ toJsaon(steps) }}          
        run: |
          echo "${step1}"
          echo "${step1_conc}"
          echo "${STEPS_CONTEXT}"
          