name: Healthcheck

on: [push]
# below block is run every 5 mins and every 7 mins
#  schedule:
#    - cron: "0/5 * * * *"
#    - cron: "0/7 * * * *"

jobs:
  run-health-check:
    strategy:
      matrix:
        runner: [macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: desktop disk-usage 
        id: desktop_disk_usage
        run:
          du -hH -d 1 ~/Desktop
      - name: Library disk-usage
        id: Library_disk_usage
        run:
          du -hH -d 1 ~/Library/Developer
      - name: cpu usage
        id: cpu_usage
        run:
          ps -A -o %cpu | awk '{s+=$1} END {print "CPU " s "%"}'
      - name: memory usage
        id: memory_usage
        run:
          ps -A -o %mem | awk '{s+=$1} END {print "Memory " s "%"}'
      - name: notifications
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          Steps_Contexts: ${{ toJSON(steps) }}
        run: |
          curl -X POST -H 'Content-type: application/json' -- data '{"text": "Job Output ${Steps_Contexts}'
