name: Healthcheck

on: [push, workflow_dispatch]

jobs:
  run-health-check:
    runs-on: macos-latest
    steps:
      - name: desktop disk-usage 
        run:
          du -hH -d 1 ~/Desktop
      - name: Library disk-usage
        run:
          du -hH -d 1 ~/Library/Developer
      - name: cpu usage 
        run:
          ps -A -o %cpu | awk '{s+=$1} END {print "CPU " s "%"}'
      - name: memory usage
        run:
          ps -A -o %mem | awk '{s+=$1} END {print "Memory " s "%"}'
       