name: Healthcheck

on: [push]
# below block is run every 5 mins and every 7 mins
#  schedule:
#    - cron: "0/5 * * * *"
#    - cron: "0/7 * * * *"

jobs:
  run-health-check:
    strategy:
      matrix:
        runner: [macos-latest]
    runs-on: ${{ matrix.runner }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: desktop disk-usage 
        id: Desktop-disk-usage
        run: |
          du -hH -d 1 ~/Desktop
        if: ${{ always() }}
      - name: Library disk-usage
        id: Library-disk-usage
        run: |
          du -hH -d 1 ~/Library/Developer
        if: ${{ always() }}
      - name: cpu usage
        id: CPU-usage
        run:
          ps -A -o %cpu | awk '{s+=$1} END {print "CPU " s "%"}'
        if: ${{ always() }}
      - name: memory usage
        id: Memory-usage        
        run:
          ps -A -o %mem | awk '{s+=$1} END {print "Memory " s "%"}'
        if: ${{ always() }}
      - name: Slack_notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()


          