name: Purge folders older than 7 days

on: [push]


jobs:
  purge_Folders:
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: create_directory
        id: create_directory
        run: |
          sudo mkdir -p /home/user/test1/test
          sudo mkdir -p /home/user/test2/test
          sudo mkdir -p /home/user/test3/test
        if: ${{ always() }}
      - name: Purge_folders_7_days
        id: purge
        run: |
          find ~/home/user/* -type d -mtime +7 -exec rm -rf {} \;
        if: ${{ always() }}

