name: test_ruby

on: 
  workflow_dispatch:
    inputs:
      rubyVersion:
        description: 'Ruby Version'
        required: true
        default: '2.6.6'
      gemsVersion:
        description: 'Gems Version'
        required: true
        default: '2.6.0'

jobs:
  Installation:
    runs-on: ubuntu-latest
    steps:
    - name: Installing Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{github.event.input.rubyVersion}}
        bundler-cache: true
    - run: ruby hello.rb
     


