name: test_ruby

on: 
  workflow_dispatch:
    inputs:
      rubyVersion:
        description: 'Ruby Version'
        required: true
        default: '2.6.6'
      gemsVersion:
        description: 'Gems Version'
        required: true
        default: '2.6.0'
      installNewVersion:
        description: 'Install New Ruby version'
        required: true
        default: 'No'  

jobs:
  Installation:
    runs-on: macos-latest
    steps:
    - name: Install Brew
      run: 
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install rbenv
      run: 
        brew install rbenv
    - name: Installing Ruby
      run: 
        rbenv install ${{ github.event.inputs.rubyVersion }}
    - name: list existing ruby versions
      run: 
        rbenv versions
    - name: Install different version of ruby
      if: github.event.inputs.installNewVersion=='Yes'
      run: 
        rbenv install 3.0.1
      
  
     


