name: Purge folders older than 7 days

on: [push]


jobs:
  Purge Folders:
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: create directory
        id: create_directory
        run: |
          mkdir -p ~/home/user/test1/test
          mkdir -p ~/home/user/test2/test
          mkdir -p ~/home/user/test3/test
        if: ${{ always() }}
      - name: Purge_folders_7_days
        id: purge
        run: |
          find ~/home/user/* -mtime +7 -type d -exec rmdir {} \;
